#require 'bundler/setup'
#Bundler.require(:default)
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
title: بازرگانی دست ورز بهترین و برترین نماینده و وارد کننده ماشین الات نساجی چرم و صنعتی 
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dastvarztrading.com"
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
#   - vendor/ruby/
languages: ["fa"]

#include:
#google_analytics: G-B6VKCZT9LN
#title: [برترین و بهترین نماینده و وارد کننده ماشین الات نساجی]
#description: [بازرگانی دست ورز]
#remote_theme: pages-themes/hacker@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

